/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { 
  Lock, 
  Trash2, 
  Download, 
  Upload, 
  AlertOctagon, 
  CheckCircle, 
  Sun, 
  Moon, 
  VolumeX, 
  Timer, 
  FileJson,
  RefreshCw,
  Fingerprint
} from 'lucide-react';
import { AppSettings, VaultEntry, SecureNote } from '../types';
import { 
  saveAppSettings, 
  clearAllVaultData, 
  getVaultEntries, 
  getSecureNotes, 
  getMasterPasswordConfig,
  saveMasterPasswordConfig,
  saveVaultEntry,
  saveSecureNote
} from '../services/db';
import { Capacitor } from '@capacitor/core';

interface SettingsScreenProps {
  settings: AppSettings;
  onSettingsUpdate: (newSettings: AppSettings) => void;
  onFactoryReset: () => void;
  masterKey: CryptoKey | null;
  userId?: string;
}

export default function SettingsScreen({ 
  settings, 
  onSettingsUpdate, 
  onFactoryReset, 
  masterKey,
  userId
}: SettingsScreenProps) {
  const [loading, setLoading] = useState(false);
  const [successMsg, setSuccessMsg] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [wipeConfirm, setWipeConfirm] = useState('');
  const [showWipeModal, setShowWipeModal] = useState(false);
  const [isBiometricAvailable, setIsBiometricAvailable] = useState(false);

  useEffect(() => {
    if (Capacitor.getPlatform() === 'android' || Capacitor.getPlatform() === 'ios') {
      checkBiometrics();
    }
  }, []);

  const checkBiometrics = async () => {
    try {
      const { isAvailable } = await (Capacitor.Plugins as any).BiometricAuth.checkBiometricSupport();
      setIsBiometricAvailable(isAvailable);
    } catch (e) {
      console.warn("Biometrics not supported:", e);
    }
  };

  const handleDisableBiometrics = async () => {
    setLoading(true);
    try {
      await (Capacitor.Plugins as any).BiometricAuth.clearMasterPassword();
      showTempSuccess('Biometric unlock disabled and credentials cleared.');
    } catch (e) {
      showTempError('Failed to clear biometric settings.');
    } finally {
      setLoading(false);
    }
  };

  // Export fully encrypted backup
  const handleExportBackup = async () => {
    setLoading(true);
    try {
      const authConfig = await getMasterPasswordConfig(userId);
      const vaultEntries = await getVaultEntries(userId);
      const secureNotes = await getSecureNotes(userId);

      if (!authConfig) {
        showTempError('No cryptographic settings detected. Cannot backup empty vault.');
        return;
      }

      const backupPackage = {
        appIdentifier: 'LocalPasswordManager',
        backupVersion: 1,
        exportedAt: Date.now(),
        cryptography: {
          salt: authConfig.salt,
          verificationHash: authConfig.verificationHash
        },
        vaultEntries,
        secureNotes
      };

      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(backupPackage, null, 2));
      const downloadAnchor = document.createElement('a');
      downloadAnchor.setAttribute("href", dataStr);
      downloadAnchor.setAttribute("download", `vault_manager_backup_${new Date().toISOString().slice(0,10)}.json`);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      downloadAnchor.remove();

      showTempSuccess('Encrypted vault exported successfully! Store it in a safe secondary location.');
    } catch (e) {
      console.error(e);
      showTempError('Failed to generate secure backup file.');
    } finally {
      setLoading(false);
    }
  };

  // Import existing backup
  const handleImportBackup = (e: React.ChangeEvent<HTMLInputElement>) => {
    const fileReader = new FileReader();
    const file = e.target.files?.[0];
    if (!file) return;

    setLoading(true);
    fileReader.onload = async (event) => {
      try {
        const fileContent = event.target?.result as string;
        const parsed = JSON.parse(fileContent);

        if (parsed.appIdentifier !== 'LocalPasswordManager' || !parsed.cryptography) {
          showTempError('Invalid backup file. This file was not generated by local password manager.');
          setLoading(false);
          return;
        }

        // Confirm master key consistency if already unlocked
        const currentConfig = await getMasterPasswordConfig(userId);
        if (currentConfig && currentConfig.verificationHash !== parsed.cryptography.verificationHash) {
          showTempError('Security Mismatch: The imported backup employs a DIFFERENT Master Password than your active configured vault.');
          setLoading(false);
          return;
        }

        // Apply backup values
        await saveMasterPasswordConfig(parsed.cryptography, userId);
        
        // Restore vault entries
        if (parsed.vaultEntries && Array.isArray(parsed.vaultEntries)) {
          for (const entry of parsed.vaultEntries as VaultEntry[]) {
            await saveVaultEntry(entry, userId);
          }
        }

        // Restore secure notes
        if (parsed.secureNotes && Array.isArray(parsed.secureNotes)) {
          for (const note of parsed.secureNotes as SecureNote[]) {
            await saveSecureNote(note, userId);
          }
        }

        showTempSuccess(`Vault restored! Imported ${parsed.vaultEntries?.length || 0} password entries and ${parsed.secureNotes?.length || 0} secure notes.`);
        // Reload app data
        setTimeout(() => {
          window.location.reload();
        }, 1500);

      } catch (err) {
        console.error(err);
        showTempError('Failed to parse backup JSON. File is corrupted or modified.');
      } finally {
        setLoading(false);
      }
    };
    fileReader.readAsText(file);
  };

  const handleFullWipe = async () => {
    if (wipeConfirm.trim().toUpperCase() !== 'WIPE') {
      showTempError('Please type WIPE to confirm operation.');
      return;
    }

    setLoading(true);
    try {
      await clearAllVaultData(userId);
      setShowWipeModal(false);
      setWipeConfirm('');
      showTempSuccess('Database completely destroyed. Hard factory reset completed.');
      setTimeout(() => {
        onFactoryReset();
      }, 1000);
    } catch (err) {
      console.error(err);
      showTempError('Failed to full wipe client database.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-2xl mx-auto" id="settings-view">
      
      {successMsg && (
        <div className="p-3.5 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-700 dark:text-emerald-400 border border-emerald-200/50 dark:border-red-900/30 rounded-xl text-xs flex items-center gap-2 animate-fade-in" id="settings-success-alert">
          <CheckCircle className="w-4 h-4" />
          <span className="font-medium">{successMsg}</span>
        </div>
      )}

      {errorMsg && (
        <div className="p-3.5 bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400 border border-red-200/50 dark:border-red-900/30 rounded-xl text-xs flex items-center gap-2 animate-pulse" id="settings-error-alert">
          <AlertOctagon className="w-4 h-4" />
          <span className="font-medium">{errorMsg}</span>
        </div>
      )}

      {/* Theme Option card */}
      <div className="bg-white dark:bg-zinc-950 border border-slate-250/60 dark:border-zinc-900 p-5 rounded-2xl shadow-xs">
        <h3 className="text-sm font-semibold text-slate-800 dark:text-zinc-200 mb-4 flex items-center gap-2">
          <Sun className="w-4.5 h-4.5 text-indigo-550 dark:text-indigo-400" />
          Appearance Settings
        </h3>
        
        <div className="flex gap-3">
          <button
            onClick={() => handleThemeChange('light')}
            className={`flex-1 flex items-center justify-center gap-2 py-3 px-4 rounded-xl border text-xs font-semibold transition-all cursor-pointer ${
              settings.theme === 'light'
                ? 'bg-indigo-50 dark:bg-indigo-950/40 text-indigo-700 border-indigo-150 dark:text-indigo-300 dark:border-indigo-900/60 shadow-xs'
                : 'bg-white dark:bg-zinc-950 text-slate-500 border-slate-200 dark:border-zinc-850 hover:bg-slate-55 dark:hover:bg-zinc-900'
            }`}
            id="btn-settings-theme-light"
          >
            <Sun className="w-4 h-4" />
            <span>Light Interface</span>
          </button>
          
          <button
            onClick={() => handleThemeChange('dark')}
            className={`flex-1 flex items-center justify-center gap-2 py-3 px-4 rounded-xl border text-xs font-semibold transition-all cursor-pointer ${
              settings.theme === 'dark'
                ? 'bg-indigo-50 dark:bg-indigo-950/40 text-indigo-700 border-indigo-150 dark:text-indigo-300 dark:border-indigo-900/60 shadow-xs'
                : 'bg-white dark:bg-zinc-950 text-slate-500 border-slate-200 dark:border-zinc-850 hover:bg-slate-55 dark:hover:bg-zinc-900'
            }`}
            id="btn-settings-theme-dark"
          >
            <Moon className="w-4 h-4" />
            <span>Dark Interface</span>
          </button>
        </div>
      </div>

      {/* Auto-Lock Settings card */}
      <div className="bg-white dark:bg-zinc-950 border border-slate-250/60 dark:border-zinc-900 p-5 rounded-2xl shadow-xs">
        <div className="flex items-center gap-2 pb-3 mb-4 border-b border-slate-100 dark:border-zinc-900">
          <Timer className="w-4.5 h-4.5 text-indigo-550 dark:text-indigo-400" />
          <h3 className="text-sm font-semibold text-slate-800 dark:text-zinc-200">
            Security Session Timeout
          </h3>
        </div>
        
        <p className="text-xs text-slate-500 dark:text-zinc-400 mb-4 leading-relaxed">
          The Vault automatically locks memory caches and destroys the ephemeral Derived Master Key after specified minutes of inactive idle state or when minimizing the app focus.
        </p>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
          {[1, 5, 15, 30, 0].map((dur) => (
            <button
              key={dur}
              onClick={() => handleAutoLockChange(dur)}
              className={`py-2 px-3 border text-center text-xs rounded-xl font-medium transition-all cursor-pointer ${
                settings.autoLockDuration === dur
                  ? 'bg-indigo-600 text-white border-indigo-600 dark:bg-indigo-600 dark:text-white dark:border-indigo-650'
                  : 'bg-white dark:bg-zinc-950 text-slate-600 dark:text-zinc-400 border-slate-200 dark:border-zinc-850 hover:bg-slate-55 dark:hover:bg-zinc-900'
              }`}
              id={`btn-lock-dur-${dur}`}
            >
              {dur === 0 ? 'Never Lock' : `${dur} Minute${dur > 1 ? 's' : ''}`}
            </button>
          ))}
        </div>
      </div>

      {/* Biometric Settings card */}
      {isBiometricAvailable && (
        <div className="bg-white dark:bg-zinc-950 border border-slate-250/60 dark:border-zinc-900 p-5 rounded-2xl shadow-xs">
          <div className="flex items-center gap-2 pb-3 mb-4 border-b border-slate-100 dark:border-zinc-900">
            <Fingerprint className="w-4.5 h-4.5 text-indigo-550 dark:text-indigo-400" />
            <h3 className="text-sm font-semibold text-slate-800 dark:text-zinc-200">
              Biometric Authentication
            </h3>
          </div>

          <p className="text-xs text-slate-500 dark:text-zinc-400 mb-4 leading-relaxed">
            Biometric unlock allows you to access your vault using your fingerprint or face recognition instead of typing your Master Password every time.
          </p>

          <button
            onClick={handleDisableBiometrics}
            disabled={loading}
            className="w-full flex items-center justify-center gap-2 bg-slate-100 dark:bg-zinc-900 hover:bg-slate-200 dark:hover:bg-zinc-850 text-slate-700 dark:text-zinc-300 py-3 px-4 rounded-xl text-xs font-semibold transition-all cursor-pointer border border-slate-200 dark:border-zinc-800"
            id="btn-settings-disable-biometric"
          >
            <Trash2 className="w-4 h-4" />
            <span>Disable Biometric Unlock & Clear Credentials</span>
          </button>
        </div>
      )}

      {/* Backup Utility card */}
      <div className="bg-white dark:bg-zinc-950 border border-slate-250/60 dark:border-zinc-900 p-5 rounded-2xl shadow-xs">
        <div className="flex items-center gap-2 pb-3 mb-4 border-b border-slate-100 dark:border-zinc-900">
          <FileJson className="w-4.5 h-4.5 text-indigo-550 dark:text-indigo-400" />
          <h3 className="text-sm font-semibold text-slate-800 dark:text-zinc-200">
            Vault Export / Import Backups
          </h3>
        </div>

        <p className="text-xs text-slate-500 dark:text-zinc-400 mb-4 leading-relaxed">
          <b>Zero-Knowledge Backup philosophy:</b> Downloaded backups are NOT in plaintext. All credentials and secret notes remain fully encrypted using your standard Master Password. Only you can load and decrypt this file using your Master Password.
        </p>

        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleExportBackup}
            disabled={loading}
            className="flex-1 flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-600 dark:hover:bg-indigo-700 text-white py-3 px-4 rounded-xl text-xs font-semibold transition-all disabled:opacity-50 cursor-pointer shadow-xs"
            id="btn-settings-export"
          >
            {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
            <span>Export Encrypted JSON Backup</span>
          </button>

          <label className="flex-1 flex items-center justify-center gap-2 border border-slate-300 dark:border-zinc-800 bg-white dark:bg-zinc-950 hover:bg-slate-55 dark:hover:bg-zinc-900 text-slate-700 dark:text-zinc-300 py-3 px-4 rounded-xl text-xs font-semibold transition-all cursor-pointer select-none">
            <Upload className="w-4 h-4" />
            <span>Import/Restore Vault File</span>
            <input
              type="file"
              accept=".json"
              onChange={handleImportBackup}
              disabled={loading}
              className="hidden"
              id="file-settings-import-hidden"
            />
          </label>
        </div>
      </div>

      {/* Extreme Destructive Area */}
      <div className="bg-red-50/50 dark:bg-red-950/10 border border-red-100 dark:border-red-950 p-5 rounded-2xl">
        <div className="flex items-start gap-3">
          <Trash2 className="w-5 h-5 text-red-600 dark:text-red-400 shrink-0 mt-0.5" />
          <div className="space-y-4 flex-1">
            <div>
              <h3 className="text-sm font-bold text-red-800 dark:text-red-400">Danger: Destroy Vault</h3>
              <p className="text-xs text-red-700 dark:text-zinc-400 mt-1 leading-relaxed">
                Factory resetting clears the entire IndexedDB data repository on this device, deleting your Master Password configuration, salt, all credentials, and secure notes. This is irreversible. If you do not have an exported backup, your data is lost forever.
              </p>
            </div>

            {!showWipeModal ? (
              <button
                onClick={() => setShowWipeModal(true)}
                className="bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded-xl text-xs font-semibold shadow-xs transition-colors cursor-pointer"
                id="btn-settings-request-wipe"
              >
                Permanently Wipe Entire Database
              </button>
            ) : (
              <div className="bg-white dark:bg-zinc-950 border border-red-200 dark:border-red-950/60 p-4 rounded-xl space-y-3 shadow-md max-w-md">
                <p className="text-xs font-semibold text-slate-800 dark:text-zinc-200">
                  Are you absolutely certain? To confirm, type <span className="font-mono text-red-600 dark:text-red-400 font-bold">WIPE</span> below:
                </p>
                <input
                  type="text"
                  placeholder="Type WIPE"
                  value={wipeConfirm}
                  onChange={(e) => setWipeConfirm(e.target.value)}
                  className="block w-full py-2 px-3 text-xs bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-lg focus:ring-red-500 focus:border-red-500 dark:text-zinc-200 font-mono"
                  id="settings-wipe-confirm-input"
                />
                <div className="flex gap-2">
                  <button
                    onClick={handleFullWipe}
                    className="bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded-lg text-xs font-semibold transition-all flex-1 cursor-pointer animate-pulse"
                    id="btn-settings-confirm-wipe"
                  >
                    Yes, Delete Everything
                  </button>
                  <button
                    onClick={() => {
                      setShowWipeModal(false);
                      setWipeConfirm('');
                    }}
                    className="border border-slate-200 dark:border-zinc-800 text-slate-600 dark:text-zinc-400 py-2 px-3 rounded-lg text-xs font-semibold hover:bg-slate-55 cursor-pointer"
                    id="btn-settings-cancel-wipe"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

    </div>
  );
}
